version: "3.9"
services:
  web:
    image: nginx:1.19.6
    ports:
    - "8080:80"
    volumes:
    - ./configs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./configs/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - /usr/local/report/site:/usr/share/nginx/html
